/*
 * JS for ContactsScreen generated by Appery.io
 */

Apperyio.getProjectGUID = function() {
    return '3c9f60c6-b847-44b2-a4b1-8c9fb6f4fa73';
};

function navigateTo(outcome, useAjax) {
    Apperyio.navigateTo(outcome, useAjax);
}

function adjustContentHeight() {
    Apperyio.adjustContentHeightWithPadding();
}

function adjustContentHeightWithPadding(_page) {
    Apperyio.adjustContentHeightWithPadding(_page);
}

function setDetailContent(pageUrl) {
    Apperyio.setDetailContent(pageUrl);
}

Apperyio.AppPages = [{
    "name": "singIn",
    "location": "singIn.html"
}, {
    "name": "ContactsScreen",
    "location": "ContactsScreen.html"
}, {
    "name": "Twilio_Send",
    "location": "Twilio_Send.html"
}, {
    "name": "startPage",
    "location": "startPage.html"
}, {
    "name": "Twilio_Messages",
    "location": "Twilio_Messages.html"
}, {
    "name": "updateDB_page",
    "location": "updateDB_page.html"
}];

function ContactsScreen_js() {

    /* Object & array with components "name-to-id" mapping */
    var n2id_buf = {
        'query_input': 'ContactsScreen_query_input',
        'search_button': 'ContactsScreen_search_button',
        'contacts_list': 'ContactsScreen_contacts_list',
        'contacts_item': 'ContactsScreen_contacts_item',
        'mobilelistitembutton_22': 'ContactsScreen_mobilelistitembutton_22',
        'mobilegrid_27': 'ContactsScreen_mobilegrid_27',
        'mobilegridcell_28': 'ContactsScreen_mobilegridcell_28',
        'mobilelabel_32': 'ContactsScreen_mobilelabel_32',
        'mobilegridcell_29': 'ContactsScreen_mobilegridcell_29',
        'cotact_name': 'ContactsScreen_cotact_name',
        'mobilegridcell_30': 'ContactsScreen_mobilegridcell_30',
        'mobilelabel_33': 'ContactsScreen_mobilelabel_33',
        'mobilegridcell_31': 'ContactsScreen_mobilegridcell_31',
        'phone_number': 'ContactsScreen_phone_number'
    };

    if ("n2id" in window && window.n2id !== undefined) {
        $.extend(n2id, n2id_buf);
    } else {
        window.n2id = n2id_buf;
    }

    /*
     * Nonvisual components
     */

    Apperyio.mappings = Apperyio.mappings || {};

    Apperyio.mappings["ContactsScreen_contacts_service_onbeforesend_mapping_0"] = {
        "homeScreen": "ContactsScreen",
        "directions": [

        {
            "from_name": "ContactsScreen",
            "from_type": "UI",

            "to_name": "contacts_service",
            "to_type": "SERVICE_REQUEST",

            "to_default": {
                "data": {
                    "options": {
                        "multiple": true
                    },
                    "params": {
                        "fields": "*"
                    }
                }
            },

            "mappings": [

            {

                "source": "$['query_input:text']",
                "target": "$['data']['options']['filter']"

            }

            ]
        }

        ]
    };

    Apperyio.mappings["ContactsScreen_contacts_service_onsuccess_mapping_0"] = {
        "homeScreen": "ContactsScreen",
        "directions": [

        {
            "from_name": "contacts_service",
            "from_type": "SERVICE_RESPONSE",

            "to_name": "ContactsScreen",
            "to_type": "UI",

            "mappings": [

            {

                "source": "$['data'][i]",
                "target": "$['contacts_item']"

            },

            {

                "source": "$['data'][i]['name']['formatted']",
                "target": "$['contacts_item']['cotact_name:text']"

            },

            {

                "source": "$['data'][i]['phoneNumbers'][0]['value']",
                "target": "$['contacts_item']['phone_number:text']"

            }

            ]
        }

        ]
    };

    Apperyio.datasources = Apperyio.datasources || {};

    window.contacts_service = Apperyio.datasources.contacts_service = new Apperyio.DataSource(ContactsService, {
        "onBeforeSend": function(jqXHR) {
            Apperyio.processMappingAction(Apperyio.mappings["ContactsScreen_contacts_service_onbeforesend_mapping_0"]);
        },
        "onComplete": function(jqXHR, textStatus) {

        },
        "onSuccess": function(data) {
            Apperyio.processMappingAction(Apperyio.mappings["ContactsScreen_contacts_service_onsuccess_mapping_0"]);
        },
        "onError": function(jqXHR, textStatus, errorThrown) {}
    });

    Apperyio.CurrentScreen = 'ContactsScreen';
    _.chain(Apperyio.mappings).filter(function(m) {
        return m.homeScreen === Apperyio.CurrentScreen;
    }).each(Apperyio.UIHandler.hideTemplateComponents);

    /*
     * Events and handlers
     */

    // On Load
    var ContactsScreen_onLoad = function() {
            ContactsScreen_elementsExtraJS();

            ContactsScreen_deviceEvents();
            ContactsScreen_windowEvents();
            ContactsScreen_elementsEvents();
        };

    // screen window events


    function ContactsScreen_windowEvents() {

        $('#ContactsScreen').bind('pageshow orientationchange', function() {
            var _page = this;
            adjustContentHeightWithPadding(_page);
        });

    };

    // device events


    function ContactsScreen_deviceEvents() {
        document.addEventListener("deviceready", function() {

        });
    };

    // screen elements extra js


    function ContactsScreen_elementsExtraJS() {
        // screen (ContactsScreen) extra code

        /* contacts_list */

        listView = $("#ContactsScreen_contacts_list");
        theme = listView.attr("data-theme");
        if (typeof theme !== 'undefined') {
            var themeClass = "ui-btn-up-" + theme;
            listItem = $("#ContactsScreen_contacts_list .ui-li-static");
            $.each(listItem, function(index, value) {
                $(this).addClass(themeClass);
            });
        }

        /* contacts_item */

    };

    // screen elements handler


    function ContactsScreen_elementsEvents() {
        $(document).on("click", "a :input,a a,a fieldset label", function(event) {
            event.stopPropagation();
        });

        $(document).off("click", '#ContactsScreen_mobilecontainer [name="search_button"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    try {
                        contacts_service.execute({});
                    } catch (e) {
                        console.error(e);
                        hideSpinner();
                    };

                }
            },
        }, '#ContactsScreen_mobilecontainer [name="search_button"]');

    };

    $(document).off("pagebeforeshow", "#ContactsScreen").on("pagebeforeshow", "#ContactsScreen", function(event, ui) {
        Apperyio.CurrentScreen = "ContactsScreen";
        _.chain(Apperyio.mappings).filter(function(m) {
            return m.homeScreen === Apperyio.CurrentScreen;
        }).each(Apperyio.UIHandler.hideTemplateComponents);
    });

    ContactsScreen_onLoad();
};

$(document).off("pagecreate", "#ContactsScreen").on("pagecreate", "#ContactsScreen", function(event, ui) {
    Apperyio.processSelectMenu($(this));
    ContactsScreen_js();
});