/*
 * JS for startPage generated by Appery.io
 */

Apperyio.getProjectGUID = function() {
    return '3c9f60c6-b847-44b2-a4b1-8c9fb6f4fa73';
};

function navigateTo(outcome, useAjax) {
    Apperyio.navigateTo(outcome, useAjax);
}

function adjustContentHeight() {
    Apperyio.adjustContentHeightWithPadding();
}

function adjustContentHeightWithPadding(_page) {
    Apperyio.adjustContentHeightWithPadding(_page);
}

function setDetailContent(pageUrl) {
    Apperyio.setDetailContent(pageUrl);
}

// Appery.io push registration service
var _pushRegistrationApperyService = new Apperyio.RestService({
    'url': 'https://api.appery.io/rest/push/reg',
    'dataType': 'json',
    'type': 'post',
    'contentType': 'application/json',
});

Apperyio.AppPages = [{
    "name": "singIn",
    "location": "singIn.html"
}, {
    "name": "ContactsScreen",
    "location": "ContactsScreen.html"
}, {
    "name": "Twilio_Send",
    "location": "Twilio_Send.html"
}, {
    "name": "startPage",
    "location": "startPage.html"
}, {
    "name": "Twilio_Messages",
    "location": "Twilio_Messages.html"
}, {
    "name": "updateDB_page",
    "location": "updateDB_page.html"
}];

function startPage_js() {

    /* Object & array with components "name-to-id" mapping */
    var n2id_buf = {
        'invite_friends': 'startPage_invite_friends',
        'show_my_location': 'startPage_show_my_location',
        'google_map': 'startPage_google_map',
        'marker_3': 'startPage_marker_3',
        'from': 'startPage_from',
        'to': 'startPage_to',
        'mobilelist_12': 'startPage_mobilelist_12',
        'mobilelistitem_31': 'startPage_mobilelistitem_31',
        'mobilegrid_19': 'startPage_mobilegrid_19',
        'mobilegridcell_20': 'startPage_mobilegridcell_20',
        'show_directions': 'startPage_show_directions',
        'mobilegridcell_21': 'startPage_mobilegridcell_21',
        'show_traffic': 'startPage_show_traffic',
        'mobilegridcell_26': 'startPage_mobilegridcell_26',
        'get_markers': 'startPage_get_markers',
        'mobilelistitembutton_32': 'startPage_mobilelistitembutton_32',
        'mobilelist_33': 'startPage_mobilelist_33',
        'mobilelistitem_34': 'startPage_mobilelistitem_34',
        'mobilelistitembutton_35': 'startPage_mobilelistitembutton_35',
        'park_name': 'startPage_park_name',
        'takephoto': 'startPage_takephoto',
        'photopreview': 'startPage_photopreview',
        'mobilebutton_4': 'startPage_mobilebutton_4'
    };

    if ("n2id" in window && window.n2id !== undefined) {
        $.extend(n2id, n2id_buf);
    } else {
        window.n2id = n2id_buf;
    }

    /*
     * Nonvisual components
     */

    Apperyio.mappings = Apperyio.mappings || {};

    Apperyio.mappings["startPage_convert_address_onbeforesend_mapping_0"] = {
        "homeScreen": "startPage",
        "directions": [

        {

            "to_name": "convert_address",
            "to_type": "SERVICE_REQUEST",

            "to_default": {
                "headers": {},
                "parameters": {
                    "address": "Canton MD",
                    "sensor": "false"
                },
                "body": null
            },

            "mappings": []
        }

        ]
    };

    Apperyio.mappings["startPage_convert_address_onsuccess_mapping_0"] = {
        "homeScreen": "startPage",
        "directions": [

        {
            "from_name": "convert_address",
            "from_type": "SERVICE_RESPONSE",

            "to_name": "markerLat",
            "to_type": "LOCAL_STORAGE",

            "mappings": [

            {

                "source": "$['body']['results'][0]['geometry']['location']['lat']",
                "target": "$"

            }

            ]
        },

        {
            "from_name": "convert_address",
            "from_type": "SERVICE_RESPONSE",

            "to_name": "markerLng",
            "to_type": "LOCAL_STORAGE",

            "mappings": [

            {

                "source": "$['body']['results'][0]['geometry']['location']['lng']",
                "target": "$"

            }

            ]
        }

        ]
    };

    Apperyio.mappings["startPage_get_db_locations_onbeforesend_mapping_0"] = {
        "homeScreen": "startPage",
        "directions": [

        {

            "to_name": "get_db_locations",
            "to_type": "SERVICE_REQUEST",

            "to_default": {
                "headers": {
                    "X-Appery-Database-Id": "{database_id}"
                },
                "parameters": {},
                "body": null
            },

            "mappings": []
        }

        ]
    };

    Apperyio.mappings["startPage_get_db_locations_onsuccess_mapping_0"] = {
        "homeScreen": "startPage",
        "directions": []
    };

    Apperyio.mappings["startPage_geolocation1_onsuccess_mapping_0"] = {
        "homeScreen": "startPage",
        "directions": [

        {
            "from_name": "geolocation1",
            "from_type": "SERVICE_RESPONSE",

            "to_name": "currentLat",
            "to_type": "LOCAL_STORAGE",

            "mappings": [

            {

                "source": "$['data']['coords']['latitude']",
                "target": "$"

            }

            ]
        },

        {
            "from_name": "geolocation1",
            "from_type": "SERVICE_RESPONSE",

            "to_name": "currentLng",
            "to_type": "LOCAL_STORAGE",

            "mappings": [

            {

                "source": "$['data']['coords']['longitude']",
                "target": "$"

            }

            ]
        }

        ]
    };

    Apperyio.mappings["startPage_geolocation1_onbeforesend_mapping_0"] = {
        "homeScreen": "startPage",
        "directions": [

        {

            "to_name": "geolocation1",
            "to_type": "SERVICE_REQUEST",

            "to_default": {
                "data": {
                    "options": {
                        "maximumAge": 3000,
                        "timeout": 5000,
                        "enableHighAccuracy": true,
                        "watchPosition": false
                    }
                }
            },

            "mappings": []
        }

        ]
    };

    Apperyio.mappings["startPage_camera_shot_onsuccess_mapping_0"] = {
        "homeScreen": "startPage",
        "directions": [

        {
            "from_name": "camera_shot",
            "from_type": "SERVICE_RESPONSE",

            "to_name": "startPage",
            "to_type": "UI",

            "mappings": [

            {

                "source": "$['data']['imageDataBase64']",
                "target": "$['photopreview:image']"

            }

            ]
        }

        ]
    };

    Apperyio.mappings["startPage_camera_shot_onbeforesend_mapping_0"] = {
        "homeScreen": "startPage",
        "directions": [

        {

            "to_name": "camera_shot",
            "to_type": "SERVICE_REQUEST",

            "to_default": {
                "data": {
                    "quality": 80,
                    "destinationType": "Data URL",
                    "sourceType": "Camera",
                    "allowEdit": true,
                    "encodingType": "JPEG",
                    "targetWidth": 1024,
                    "targetHeight": 768
                }
            },

            "mappings": []
        }

        ]
    };

    Apperyio.mappings["startPage_geolocation2_onsuccess_mapping_0"] = {
        "homeScreen": "startPage",
        "directions": []
    };

    Apperyio.mappings["startPage_geolocation2_onbeforesend_mapping_0"] = {
        "homeScreen": "startPage",
        "directions": [

        {

            "to_name": "geolocation2",
            "to_type": "SERVICE_REQUEST",

            "to_default": {
                "data": {
                    "options": {
                        "maximumAge": 3000,
                        "timeout": 5000,
                        "enableHighAccuracy": true,
                        "watchPosition": false
                    }
                }
            },

            "mappings": []
        }

        ]
    };

    Apperyio.mappings["startPage_restservice1_onsuccess_mapping_0"] = {
        "homeScreen": "startPage",
        "directions": [

        {
            "from_name": "restservice1",
            "from_type": "SERVICE_RESPONSE",

            "to_name": "startPage",
            "to_type": "UI",

            "mappings": [

            {

                "source": "$['body'][i]",
                "target": "$['mobilelistitem_34']"

            },

            {

                "source": "$['body'][i]['location']",
                "target": "$['mobilelistitem_34']['park_name:text']"

            }

            ]
        }

        ]
    };

    Apperyio.mappings["startPage_restservice1_onbeforesend_mapping_0"] = {
        "homeScreen": "startPage",
        "directions": [

        {

            "to_name": "restservice1",
            "to_type": "SERVICE_REQUEST",

            "to_default": {
                "headers": {
                    "X-Appery-Database-Id": "{database_id}"
                },
                "parameters": {},
                "body": null
            },

            "mappings": []
        }

        ]
    };

    Apperyio.datasources = Apperyio.datasources || {};

    window.convert_address = Apperyio.datasources.convert_address = new Apperyio.DataSource(ConvertAddress, {
        "onBeforeSend": function(jqXHR) {
            Apperyio.processMappingAction(Apperyio.mappings["startPage_convert_address_onbeforesend_mapping_0"]);
        },
        "onComplete": function(jqXHR, textStatus) {

        },
        "onSuccess": function(data) {
            Apperyio.processMappingAction(Apperyio.mappings["startPage_convert_address_onsuccess_mapping_0"]);
            var markerLatLng = new google.maps.LatLng(localStorage.getItem('markerLat'), localStorage.getItem('markerLng'));

            var marker = new google.maps.Marker({
                position: markerLatLng,
                map: map,
                title: data.results[0].address_components[0].long_name,
                animation: google.maps.Animation.DROP
            });

            bounds.extend(markerLatLng);
            map.fitBounds(bounds);
        },
        "onError": function(jqXHR, textStatus, errorThrown) {}
    });

    window.get_db_locations = Apperyio.datasources.get_db_locations = new Apperyio.DataSource(locations_ParkFinder_list_service, {
        "onBeforeSend": function(jqXHR) {
            Apperyio.processMappingAction(Apperyio.mappings["startPage_get_db_locations_onbeforesend_mapping_0"]);
        },
        "onComplete": function(jqXHR, textStatus) {

        },
        "onSuccess": function(data) {
            Apperyio.processMappingAction(Apperyio.mappings["startPage_get_db_locations_onsuccess_mapping_0"]);
            for (var i = 0; i < data.length; i++) {
                convert_address.execute({
                    'data': {
                        'address': data[i].location,
                        'sensor': false
                    }
                });
            };
        },
        "onError": function(jqXHR, textStatus, errorThrown) {}
    });

    window.geolocation1 = Apperyio.datasources.geolocation1 = new Apperyio.DataSource(GeolocationService, {
        "onBeforeSend": function(jqXHR) {
            Apperyio.processMappingAction(Apperyio.mappings["startPage_geolocation1_onbeforesend_mapping_0"]);
        },
        "onComplete": function(jqXHR, textStatus) {

        },
        "onSuccess": function(data) {
            Apperyio.processMappingAction(Apperyio.mappings["startPage_geolocation1_onsuccess_mapping_0"]);
            var markerLatLng = new google.maps.LatLng(Apperyio.storage.currentLat.get(), Apperyio.storage.currentLng.get());

            var marker = new google.maps.Marker({
                position: markerLatLng,
                map: map,
                icon: 'http://i.imgur.com/fDUI8bZ.png'
            });

            map.setCenter(markerLatLng);
            map.setZoom(15);
        },
        "onError": function(jqXHR, textStatus, errorThrown) {}
    });

    window.camera_shot = Apperyio.datasources.camera_shot = new Apperyio.DataSource(CameraService, {
        "onBeforeSend": function(jqXHR) {
            Apperyio.processMappingAction(Apperyio.mappings["startPage_camera_shot_onbeforesend_mapping_0"]);
        },
        "onComplete": function(jqXHR, textStatus) {

        },
        "onSuccess": function(data) {
            Apperyio.processMappingAction(Apperyio.mappings["startPage_camera_shot_onsuccess_mapping_0"]);
        },
        "onError": function(jqXHR, textStatus, errorThrown) {}
    });

    window.geolocation2 = Apperyio.datasources.geolocation2 = new Apperyio.DataSource(GeolocationService, {
        "onBeforeSend": function(jqXHR) {
            Apperyio.processMappingAction(Apperyio.mappings["startPage_geolocation2_onbeforesend_mapping_0"]);
        },
        "onComplete": function(jqXHR, textStatus) {

        },
        "onSuccess": function(data) {
            Apperyio.processMappingAction(Apperyio.mappings["startPage_geolocation2_onsuccess_mapping_0"]);
        },
        "onError": function(jqXHR, textStatus, errorThrown) {}
    });

    window.restservice1 = Apperyio.datasources.restservice1 = new Apperyio.DataSource(locations_ParkFinder_list_service, {
        "onBeforeSend": function(jqXHR) {
            Apperyio.processMappingAction(Apperyio.mappings["startPage_restservice1_onbeforesend_mapping_0"]);
        },
        "onComplete": function(jqXHR, textStatus) {

        },
        "onSuccess": function(data) {
            Apperyio.processMappingAction(Apperyio.mappings["startPage_restservice1_onsuccess_mapping_0"]);
        },
        "onError": function(jqXHR, textStatus, errorThrown) {}
    });

    /*
     * Appery.io Push-notification registration service
     */
    Apperyio.mappings["_pushRegistrationApperyService_onbeforesend"] = {
        "homeScreen": "startPage",
        "directions": [{
            "from_name": "pushNotificationToken",
            "from_type": "LOCAL_STORAGE",
            "to_name": "_registerPushApperyDS",
            "to_type": "SERVICE_REQUEST",
            "mappings": [{
                "source": "$",
                "target": "$['body']['token']"
            }]
        }, {
            "from_name": "pushNotificationDeviceID",
            "from_type": "LOCAL_STORAGE",
            "to_name": "_registerPushApperyDS",
            "to_type": "SERVICE_REQUEST",
            "mappings": [{
                "source": "$",
                "target": "$['body']['deviceID']"
            }]
        }, {
            "from_name": "deviceTimeZone",
            "from_type": "LOCAL_STORAGE",
            "to_name": "_registerPushApperyDS",
            "to_type": "SERVICE_REQUEST",
            "mappings": [{
                "source": "$",
                "target": "$['body']['timeZone']"
            }]
        }, {
            "to_name": "_registerPushApperyDS",
            "to_type": "SERVICE_REQUEST",
            "mappings": [{
                "target_transformation": function(value) {
                    return Apperyio.getProjectGUID();
                },
                "target": "$['headers']['X-Appery-App-Id']"
            }, {
                "target_transformation": function(value) {
                    return Apperyio.getTargetPlatform();
                },
                "target": "$['body']['type']"
            }]
        }]
    };

    var _registerPushApperyDS = Apperyio.datasources._registerPushApperyDS = new Apperyio.DataSource(_pushRegistrationApperyService, {
        "onBeforeSend": function(jqXHR) {
            Apperyio.processMappingAction(Apperyio.mappings["_pushRegistrationApperyService_onbeforesend"]);
        },
        'onComplete': function(jqXHR, textStatus) {},
        'onSuccess': function(data) {
            console.info('App successfully registered with Appery.io Push service');
            $(document).trigger('pushregistrationsuccess');
        },
        'onError': function(jqXHR, textStatus, errorThrown) {
            $(document).trigger('pushregistrationfail');
        }
    });

    Apperyio.CurrentScreen = 'startPage';
    _.chain(Apperyio.mappings).filter(function(m) {
        return m.homeScreen === Apperyio.CurrentScreen;
    }).each(Apperyio.UIHandler.hideTemplateComponents);

    /*
     * Events and handlers
     */

    // On Load
    var startPage_onLoad = function() {
            startPage_elementsExtraJS();

            initialize();
            try {
                restservice1.execute({});
            } catch (e) {
                console.error(e);
                hideSpinner();
            };

            startPage_deviceEvents();
            startPage_windowEvents();
            startPage_elementsEvents();
        };

    // screen window events


    function startPage_windowEvents() {

        $('#startPage').bind('pageshow orientationchange', function() {
            var _page = this;
            adjustContentHeightWithPadding(_page);
        });

    };

    // device events


    function startPage_deviceEvents() {
        document.addEventListener("deviceready", function() {

            $(document).bind("pushinit", function() {
                localStorage.setItem('pushNotificationToken', arguments[1].registrationId);
                _registerPushApperyDS.execute({});
            });

            localStorage.setItem('pushNotificationDeviceID', device.uuid);

            var offset = new Date().getTimezoneOffset();
            var hr = parseInt(offset / (-60));
            var min = -offset - hr * 60;
            var tmin = '' + min;
            var timezone = 'UTC' + (hr > 0 ? '+' + hr : hr) + ':' + (tmin.length > 1 ? tmin : '0' + tmin);
            localStorage.setItem('deviceTimeZone', timezone);

            var push = PushNotification.init({
                ios: {
                    alert: true,
                    badge: true,
                    sound: true
                },
                android: {
                    senderID: ''
                }
            });

            push.on('registration', function(data) {
                $(document).trigger('pushinit', data);
            });

            push.on('notification', function(data) {
                $(document).trigger('push-notification', data);
            });

            push.on('error', function(e) {
                console.log("Error: " + e.message);
            });

        });
    };

    // screen elements extra js


    function startPage_elementsExtraJS() {
        // screen (startPage) extra code

        /* google_map */

        $("[name = 'google_map']").wrap("<div/>");
        $("[name = 'google_map']").parent().css("margin-left", $("[name = 'google_map']").css("margin-left"));
        $("[name = 'google_map']").parent().css("margin-right", $("[name = 'google_map']").css("margin-right"));
        $("[name = 'google_map']").css("margin-left", '0');
        $("[name = 'google_map']").css("margin-right", '0');

        var google_map_options = {
            markerSourceName: "google_map_markers",
            latitude: "",
            longitude: "",
            address: "Baltimore, MD",
            zoom: 10,
            showLocationMarker: false
        }

        Apperyio.__registerComponent('google_map', new Apperyio.ApperyMapComponent("google_map", google_map_options));
        $("[name='google_map_markers'] [apperytype='marker']").attr("reRender", "google_map");
        $(":mobile-pagecontainer").off("pagecontainershow.startPage_mobilecontainer").on("pagecontainershow.startPage_mobilecontainer", function(event, ui) {
            if (($('#startPage_google_map', ui.toPage).length > 0) && (Apperyio('google_map') != undefined)) {
                Apperyio('google_map').refresh();
            }
        });

        /* mobilelist_12 */

        listView = $("#startPage_mobilelist_12");
        theme = listView.attr("data-theme");
        if (typeof theme !== 'undefined') {
            var themeClass = "ui-btn-up-" + theme;
            listItem = $("#startPage_mobilelist_12 .ui-li-static");
            $.each(listItem, function(index, value) {
                $(this).addClass(themeClass);
            });
        }

        /* mobilelistitem_31 */

        /* mobilelist_33 */

        listView = $("#startPage_mobilelist_33");
        theme = listView.attr("data-theme");
        if (typeof theme !== 'undefined') {
            var themeClass = "ui-btn-up-" + theme;
            listItem = $("#startPage_mobilelist_33 .ui-li-static");
            $.each(listItem, function(index, value) {
                $(this).addClass(themeClass);
            });
        }

        /* mobilelistitem_34 */

    };

    // screen elements handler


    function startPage_elementsEvents() {
        $(document).on("click", "a :input,a a,a fieldset label", function(event) {
            event.stopPropagation();
        });

        $(document).off("click", '#startPage_header [name="invite_friends"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('Twilio_Send', {
                        reverse: false
                    });

                }
            },
        }, '#startPage_header [name="invite_friends"]');
        $(document).off("click", '#startPage_header [name="show_my_location"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    try {
                        geolocation1.execute({});
                    } catch (e) {
                        console.error(e);
                        hideSpinner();
                    };

                }
            },
        }, '#startPage_header [name="show_my_location"]');

        $(document).off("click", '#startPage_mobilecontainer [name="show_directions"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    var sourceAddress = Apperyio("from").val();
                    var destinationAddress = Apperyio("to").val();
                    displayDirections(sourceAddress, destinationAddress, map);

                }
            },
        }, '#startPage_mobilecontainer [name="show_directions"]');

        $(document).off("click", '#startPage_mobilecontainer [name="show_traffic"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    var trafficLayer = new google.maps.TrafficLayer();
                    trafficLayer.setMap(map);

                }
            },
        }, '#startPage_mobilecontainer [name="show_traffic"]');

        $(document).off("click", '#startPage_mobilecontainer [name="get_markers"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    try {
                        get_db_locations.execute({});
                    } catch (e) {
                        console.error(e);
                        hideSpinner();
                    };

                }
            },
        }, '#startPage_mobilecontainer [name="get_markers"]');

        $(document).off("click", '#startPage_mobilecontainer [name="takephoto"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    try {
                        camera_shot.execute({});
                    } catch (e) {
                        console.error(e);
                        hideSpinner();
                    };

                }
            },
        }, '#startPage_mobilecontainer [name="takephoto"]');

        $(document).off("click", '#startPage_mobilefooter [name="mobilebutton_4"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('singIn', {
                        reverse: false
                    });

                }
            },
        }, '#startPage_mobilefooter [name="mobilebutton_4"]');

    };

    $(document).off("pagebeforeshow", "#startPage").on("pagebeforeshow", "#startPage", function(event, ui) {
        Apperyio.CurrentScreen = "startPage";
        _.chain(Apperyio.mappings).filter(function(m) {
            return m.homeScreen === Apperyio.CurrentScreen;
        }).each(Apperyio.UIHandler.hideTemplateComponents);
    });

    startPage_onLoad();
};

$(document).off("pagecreate", "#startPage").on("pagecreate", "#startPage", function(event, ui) {
    Apperyio.processSelectMenu($(this));
    startPage_js();
});