/*
 * JS for Twilio_Messages generated by Appery.io
 */

Apperyio.getProjectGUID = function() {
    return '3c9f60c6-b847-44b2-a4b1-8c9fb6f4fa73';
};

function navigateTo(outcome, useAjax) {
    Apperyio.navigateTo(outcome, useAjax);
}

function adjustContentHeight() {
    Apperyio.adjustContentHeightWithPadding();
}

function adjustContentHeightWithPadding(_page) {
    Apperyio.adjustContentHeightWithPadding(_page);
}

function setDetailContent(pageUrl) {
    Apperyio.setDetailContent(pageUrl);
}

Apperyio.AppPages = [{
    "name": "singIn",
    "location": "singIn.html"
}, {
    "name": "ContactsScreen",
    "location": "ContactsScreen.html"
}, {
    "name": "Twilio_Send",
    "location": "Twilio_Send.html"
}, {
    "name": "startPage",
    "location": "startPage.html"
}, {
    "name": "Twilio_Messages",
    "location": "Twilio_Messages.html"
}, {
    "name": "updateDB_page",
    "location": "updateDB_page.html"
}];

function Twilio_Messages_js() {

    /* Object & array with components "name-to-id" mapping */
    var n2id_buf = {
        'mobilebutton_54': 'Twilio_Messages_mobilebutton_54',
        'mobilelist_39': 'Twilio_Messages_mobilelist_39',
        'smsList': 'Twilio_Messages_smsList',
        'mobilelistitembutton_41': 'Twilio_Messages_mobilelistitembutton_41',
        'to': 'Twilio_Messages_to',
        'from': 'Twilio_Messages_from',
        'body': 'Twilio_Messages_body',
        'sentOn': 'Twilio_Messages_sentOn',
        'mobilelist_47': 'Twilio_Messages_mobilelist_47',
        'mobilelistitem_48': 'Twilio_Messages_mobilelistitem_48',
        'mobilelistitembutton_49': 'Twilio_Messages_mobilelistitembutton_49',
        'mobilelistitem_50': 'Twilio_Messages_mobilelistitem_50',
        'mobilelistitembutton_51': 'Twilio_Messages_mobilelistitembutton_51',
        'mobilelistitem_55': 'Twilio_Messages_mobilelistitem_55',
        'mobilelistitembutton_56': 'Twilio_Messages_mobilelistitembutton_56'
    };

    if ("n2id" in window && window.n2id !== undefined) {
        $.extend(n2id, n2id_buf);
    } else {
        window.n2id = n2id_buf;
    }

    /*
     * Nonvisual components
     */

    Apperyio.mappings = Apperyio.mappings || {};

    Apperyio.mappings["Twilio_Messages_twilio_show_messages_onbeforesend_mapping_0"] = {
        "homeScreen": "Twilio_Messages",
        "directions": [

        {

            "to_name": "twilio_show_messages",
            "to_type": "SERVICE_REQUEST",

            "to_default": {
                "headers": {
                    "Authorization": "{authString}"
                },
                "parameters": {},
                "body": null
            },

            "mappings": []
        }

        ]
    };

    Apperyio.mappings["Twilio_Messages_twilio_show_messages_onsuccess_mapping_0"] = {
        "homeScreen": "Twilio_Messages",
        "directions": [

        {
            "from_name": "twilio_show_messages",
            "from_type": "SERVICE_RESPONSE",

            "to_name": "Twilio_Messages",
            "to_type": "UI",

            "mappings": [

            {

                "source": "$['body']['sms_messages'][i]",
                "target": "$['smsList']"

            },

            {

                "source": "$['body']['sms_messages'][i]['to']",
                "target_transformation": function(value, element) {
                    return "To: " + value;
                },
                "target": "$['smsList']['to:text']"

            },

            {

                "source": "$['body']['sms_messages'][i]['from']",
                "target_transformation": function(value, element) {
                    return "From: " + value;
                },
                "target": "$['smsList']['from:text']"

            },

            {

                "source": "$['body']['sms_messages'][i]['body']",
                "target": "$['smsList']['body:text']"

            },

            {

                "source": "$['body']['sms_messages'][i]['date_sent']",
                "target": "$['smsList']['sentOn:text']"

            }

            ]
        }

        ]
    };

    Apperyio.datasources = Apperyio.datasources || {};

    window.twilio_show_messages = Apperyio.datasources.twilio_show_messages = new Apperyio.DataSource(Twilio_showMessages, {
        "onBeforeSend": function(jqXHR) {
            Apperyio.processMappingAction(Apperyio.mappings["Twilio_Messages_twilio_show_messages_onbeforesend_mapping_0"]);
        },
        "onComplete": function(jqXHR, textStatus) {

        },
        "onSuccess": function(data) {
            Apperyio.processMappingAction(Apperyio.mappings["Twilio_Messages_twilio_show_messages_onsuccess_mapping_0"]);
        },
        "onError": function(jqXHR, textStatus, errorThrown) {
            alert("Error when showing sent messages: " + jqXHR.responseJSON.message);
        }
    });

    Apperyio.CurrentScreen = 'Twilio_Messages';
    _.chain(Apperyio.mappings).filter(function(m) {
        return m.homeScreen === Apperyio.CurrentScreen;
    }).each(Apperyio.UIHandler.hideTemplateComponents);

    /*
     * Events and handlers
     */

    // On Load
    var Twilio_Messages_onLoad = function() {
            Twilio_Messages_elementsExtraJS();

            Twilio_Messages_deviceEvents();
            Twilio_Messages_windowEvents();
            Twilio_Messages_elementsEvents();
        };

    // screen window events


    function Twilio_Messages_windowEvents() {

        $('#Twilio_Messages').bind('pageshow orientationchange', function() {
            var _page = this;
            adjustContentHeightWithPadding(_page);
        });
        $('#Twilio_Messages').on({
            pageshow: function(event) {
                try {
                    twilio_show_messages.execute({});
                } catch (e) {
                    console.error(e);
                    hideSpinner();
                };
                var pageName = 'TW_Home';
                var backUrl = window.location.pathname + '#' + $('[dsid="' + pageName + '"]').attr('data-url');
                var currentUrl = window.location.pathname + window.location.hash;

                history.replaceState({}, '', backUrl);

                history.pushState({}, '', currentUrl);;
            },
        });

    };

    // device events


    function Twilio_Messages_deviceEvents() {
        document.addEventListener("deviceready", function() {

        });
    };

    // screen elements extra js


    function Twilio_Messages_elementsExtraJS() {
        // screen (Twilio_Messages) extra code

        /* mobilelist_39 */

        listView = $("#Twilio_Messages_mobilelist_39");
        theme = listView.attr("data-theme");
        if (typeof theme !== 'undefined') {
            var themeClass = "ui-btn-up-" + theme;
            listItem = $("#Twilio_Messages_mobilelist_39 .ui-li-static");
            $.each(listItem, function(index, value) {
                $(this).addClass(themeClass);
            });
        }

        /* smsList */

        /* mobilelist_47 */

        listView = $("#Twilio_Messages_mobilelist_47");
        theme = listView.attr("data-theme");
        if (typeof theme !== 'undefined') {
            var themeClass = "ui-btn-up-" + theme;
            listItem = $("#Twilio_Messages_mobilelist_47 .ui-li-static");
            $.each(listItem, function(index, value) {
                $(this).addClass(themeClass);
            });
        }

        /* mobilelistitem_48 */

        /* mobilelistitem_50 */

        /* mobilelistitem_55 */

    };

    // screen elements handler


    function Twilio_Messages_elementsEvents() {
        $(document).on("click", "a :input,a a,a fieldset label", function(event) {
            event.stopPropagation();
        });

        $(document).off("click", '#Twilio_Messages_mobileheader [name="mobilebutton_54"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    $('[id="Twilio_Messages_panel_46"]').panel("open");

                }
            },
        }, '#Twilio_Messages_mobileheader [name="mobilebutton_54"]');

        $(document).off("click", '#Twilio_Messages_panel_46 [name="mobilelistitem_48"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('Twilio_Send', {
                        reverse: false
                    });

                }
            },
        }, '#Twilio_Messages_panel_46 [name="mobilelistitem_48"]');

        $(document).off("click", '#Twilio_Messages_panel_46 [name="mobilelistitem_50"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('Twilio_Messages', {
                        reverse: false
                    });

                }
            },
        }, '#Twilio_Messages_panel_46 [name="mobilelistitem_50"]');

        $(document).off("click", '#Twilio_Messages_panel_46 [name="mobilelistitem_55"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('startPage', {
                        reverse: false
                    });

                }
            },
        }, '#Twilio_Messages_panel_46 [name="mobilelistitem_55"]');

    };

    $(document).off("pagebeforeshow", "#Twilio_Messages").on("pagebeforeshow", "#Twilio_Messages", function(event, ui) {
        Apperyio.CurrentScreen = "Twilio_Messages";
        _.chain(Apperyio.mappings).filter(function(m) {
            return m.homeScreen === Apperyio.CurrentScreen;
        }).each(Apperyio.UIHandler.hideTemplateComponents);
    });

    Twilio_Messages_onLoad();
};

$(document).off("pagecreate", "#Twilio_Messages").on("pagecreate", "#Twilio_Messages", function(event, ui) {
    Apperyio.processSelectMenu($(this));
    Twilio_Messages_js();
});