/*
 * JS for Twilio_Send generated by Appery.io
 */

Apperyio.getProjectGUID = function() {
    return '3c9f60c6-b847-44b2-a4b1-8c9fb6f4fa73';
};

function navigateTo(outcome, useAjax) {
    Apperyio.navigateTo(outcome, useAjax);
}

function adjustContentHeight() {
    Apperyio.adjustContentHeightWithPadding();
}

function adjustContentHeightWithPadding(_page) {
    Apperyio.adjustContentHeightWithPadding(_page);
}

function setDetailContent(pageUrl) {
    Apperyio.setDetailContent(pageUrl);
}

Apperyio.AppPages = [{
    "name": "singIn",
    "location": "singIn.html"
}, {
    "name": "ContactsScreen",
    "location": "ContactsScreen.html"
}, {
    "name": "Twilio_Send",
    "location": "Twilio_Send.html"
}, {
    "name": "startPage",
    "location": "startPage.html"
}, {
    "name": "Twilio_Messages",
    "location": "Twilio_Messages.html"
}, {
    "name": "updateDB_page",
    "location": "updateDB_page.html"
}];

function Twilio_Send_js() {

    /* Object & array with components "name-to-id" mapping */
    var n2id_buf = {
        'mobilebutton_29': 'Twilio_Send_mobilebutton_29',
        'sendSmsTo': 'Twilio_Send_sendSmsTo',
        'sendSmsContent': 'Twilio_Send_sendSmsContent',
        'mobilebutton_13': 'Twilio_Send_mobilebutton_13',
        'mobiletextinput_137': 'Twilio_Send_mobiletextinput_137',
        'search_contacts': 'Twilio_Send_search_contacts',
        'mobilelist_121': 'Twilio_Send_mobilelist_121',
        'mobilelistitem_122': 'Twilio_Send_mobilelistitem_122',
        'mobilelistitembutton_123': 'Twilio_Send_mobilelistitembutton_123',
        'mobilegrid_128': 'Twilio_Send_mobilegrid_128',
        'mobilegridcell_129': 'Twilio_Send_mobilegridcell_129',
        'mobilelabel_133': 'Twilio_Send_mobilelabel_133',
        'mobilegridcell_130': 'Twilio_Send_mobilegridcell_130',
        'contact_name1': 'Twilio_Send_contact_name1',
        'mobilegridcell_131': 'Twilio_Send_mobilegridcell_131',
        'mobilelabel_134': 'Twilio_Send_mobilelabel_134',
        'mobilegridcell_132': 'Twilio_Send_mobilegridcell_132',
        'phone_number1': 'Twilio_Send_phone_number1',
        'mobilelist_20': 'Twilio_Send_mobilelist_20',
        'mobilelistitem_21': 'Twilio_Send_mobilelistitem_21',
        'mobilelistitembutton_22': 'Twilio_Send_mobilelistitembutton_22',
        'mobilelistitem_27': 'Twilio_Send_mobilelistitem_27',
        'mobilelistitembutton_28': 'Twilio_Send_mobilelistitembutton_28',
        'home_page': 'Twilio_Send_home_page',
        'mobilelistitembutton_57': 'Twilio_Send_mobilelistitembutton_57'
    };

    if ("n2id" in window && window.n2id !== undefined) {
        $.extend(n2id, n2id_buf);
    } else {
        window.n2id = n2id_buf;
    }

    /*
     * Nonvisual components
     */

    Apperyio.mappings = Apperyio.mappings || {};

    Apperyio.mappings["Twilio_Send_twilio_send_message_onbeforesend_mapping_0"] = {
        "homeScreen": "Twilio_Send",
        "directions": [

        {
            "from_name": "Twilio_Send",
            "from_type": "UI",

            "to_name": "twilio_send_message",
            "to_type": "SERVICE_REQUEST",

            "to_default": {
                "headers": {
                    "Content-Type": "application/x-www-form-urlencoded",
                    "Authorization": "{authString}"
                },
                "parameters": {},
                "body": {
                    "From": "{phoneNumber}"
                }
            },

            "mappings": [

            {

                "source": "$['sendSmsContent:text']",
                "target": "$['body']['Body']"

            },

            {

                "source": "$['sendSmsTo:text']",
                "target": "$['body']['To']"

            }

            ]
        }

        ]
    };

    Apperyio.mappings["Twilio_Send_contacts_service1_onsuccess_mapping_0"] = {
        "homeScreen": "Twilio_Send",
        "directions": [

        {
            "from_name": "contacts_service1",
            "from_type": "SERVICE_RESPONSE",

            "to_name": "Twilio_Send",
            "to_type": "UI",

            "mappings": [

            {

                "source": "$['data'][i]",
                "target": "$['mobilelistitem_122']"

            },

            {

                "source": "$['data'][i]['phoneNumbers'][0]['value']",
                "target": "$['mobilelistitem_122']['phone_number1:text']"

            },

            {

                "source": "$['data'][i]['name']['formatted']",
                "target": "$['mobilelistitem_122']['contact_name1:text']"

            }

            ]
        }

        ]
    };

    Apperyio.mappings["Twilio_Send_contacts_service1_onbeforesend_mapping_0"] = {
        "homeScreen": "Twilio_Send",
        "directions": [

        {
            "from_name": "Twilio_Send",
            "from_type": "UI",

            "to_name": "contacts_service1",
            "to_type": "SERVICE_REQUEST",

            "to_default": {
                "data": {
                    "options": {
                        "multiple": true
                    },
                    "params": {
                        "fields": "*"
                    }
                }
            },

            "mappings": [

            {

                "source": "$['mobiletextinput_137:text']",
                "target": "$['data']['options']['filter']"

            }

            ]
        }

        ]
    };

    Apperyio.datasources = Apperyio.datasources || {};

    window.twilio_send_message = Apperyio.datasources.twilio_send_message = new Apperyio.DataSource(Twilio_sendMessage, {
        "onBeforeSend": function(jqXHR) {
            Apperyio.processMappingAction(Apperyio.mappings["Twilio_Send_twilio_send_message_onbeforesend_mapping_0"]);
        },
        "onComplete": function(jqXHR, textStatus) {

        },
        "onSuccess": function(data) {
            alert("Message sent");
            Apperyio.navigateTo('Twilio_Messages', {
                reverse: false
            });
        },
        "onError": function(jqXHR, textStatus, errorThrown) {
            alert("Error sending message");
        }
    });

    window.contacts_service1 = Apperyio.datasources.contacts_service1 = new Apperyio.DataSource(ContactsService, {
        "onBeforeSend": function(jqXHR) {
            Apperyio.processMappingAction(Apperyio.mappings["Twilio_Send_contacts_service1_onbeforesend_mapping_0"]);
        },
        "onComplete": function(jqXHR, textStatus) {

        },
        "onSuccess": function(data) {
            Apperyio.processMappingAction(Apperyio.mappings["Twilio_Send_contacts_service1_onsuccess_mapping_0"]);
        },
        "onError": function(jqXHR, textStatus, errorThrown) {}
    });

    Apperyio.CurrentScreen = 'Twilio_Send';
    _.chain(Apperyio.mappings).filter(function(m) {
        return m.homeScreen === Apperyio.CurrentScreen;
    }).each(Apperyio.UIHandler.hideTemplateComponents);

    /*
     * Events and handlers
     */

    // On Load
    var Twilio_Send_onLoad = function() {
            Twilio_Send_elementsExtraJS();

            Twilio_Send_deviceEvents();
            Twilio_Send_windowEvents();
            Twilio_Send_elementsEvents();
        };

    // screen window events


    function Twilio_Send_windowEvents() {

        $('#Twilio_Send').bind('pageshow orientationchange', function() {
            var _page = this;
            adjustContentHeightWithPadding(_page);
        });

    };

    // device events


    function Twilio_Send_deviceEvents() {
        document.addEventListener("deviceready", function() {

        });
    };

    // screen elements extra js


    function Twilio_Send_elementsExtraJS() {
        // screen (Twilio_Send) extra code

        /* mobilelist_121 */

        listView = $("#Twilio_Send_mobilelist_121");
        theme = listView.attr("data-theme");
        if (typeof theme !== 'undefined') {
            var themeClass = "ui-btn-up-" + theme;
            listItem = $("#Twilio_Send_mobilelist_121 .ui-li-static");
            $.each(listItem, function(index, value) {
                $(this).addClass(themeClass);
            });
        }

        /* mobilelistitem_122 */

        /* mobilelist_20 */

        listView = $("#Twilio_Send_mobilelist_20");
        theme = listView.attr("data-theme");
        if (typeof theme !== 'undefined') {
            var themeClass = "ui-btn-up-" + theme;
            listItem = $("#Twilio_Send_mobilelist_20 .ui-li-static");
            $.each(listItem, function(index, value) {
                $(this).addClass(themeClass);
            });
        }

        /* mobilelistitem_21 */

        /* mobilelistitem_27 */

        /* home_page */

    };

    // screen elements handler


    function Twilio_Send_elementsEvents() {
        $(document).on("click", "a :input,a a,a fieldset label", function(event) {
            event.stopPropagation();
        });

        $(document).off("click", '#Twilio_Send_mobileheader [name="mobilebutton_29"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    $('[id="Twilio_Send_panel_19"]').panel("open");

                }
            },
        }, '#Twilio_Send_mobileheader [name="mobilebutton_29"]');

        $(document).off("click", '#Twilio_Send_mobilecontainer1 [name="mobilebutton_13"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    try {
                        twilio_send_message.execute({});
                    } catch (e) {
                        console.error(e);
                        hideSpinner();
                    };

                }
            },
        }, '#Twilio_Send_mobilecontainer1 [name="mobilebutton_13"]');

        $(document).off("click", '#Twilio_Send_mobilecontainer1 [name="search_contacts"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    try {
                        contacts_service1.execute({});
                    } catch (e) {
                        console.error(e);
                        hideSpinner();
                    };

                }
            },
        }, '#Twilio_Send_mobilecontainer1 [name="search_contacts"]');

        $(document).off("click", '#Twilio_Send_panel_19 [name="mobilelistitem_21"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('Twilio_Send', {
                        reverse: false
                    });

                }
            },
        }, '#Twilio_Send_panel_19 [name="mobilelistitem_21"]');

        $(document).off("click", '#Twilio_Send_panel_19 [name="mobilelistitem_27"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('Twilio_Messages', {
                        reverse: false
                    });

                }
            },
        }, '#Twilio_Send_panel_19 [name="mobilelistitem_27"]');

        $(document).off("click", '#Twilio_Send_panel_19 [name="home_page"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('startPage', {
                        reverse: false
                    });

                }
            },
        }, '#Twilio_Send_panel_19 [name="home_page"]');

    };

    $(document).off("pagebeforeshow", "#Twilio_Send").on("pagebeforeshow", "#Twilio_Send", function(event, ui) {
        Apperyio.CurrentScreen = "Twilio_Send";
        _.chain(Apperyio.mappings).filter(function(m) {
            return m.homeScreen === Apperyio.CurrentScreen;
        }).each(Apperyio.UIHandler.hideTemplateComponents);
    });

    Twilio_Send_onLoad();
};

$(document).off("pagecreate", "#Twilio_Send").on("pagecreate", "#Twilio_Send", function(event, ui) {
    Apperyio.processSelectMenu($(this));
    Twilio_Send_js();
});