/*
 * JS for updateDB_page generated by Appery.io
 */

Apperyio.getProjectGUID = function() {
    return '3c9f60c6-b847-44b2-a4b1-8c9fb6f4fa73';
};

function navigateTo(outcome, useAjax) {
    Apperyio.navigateTo(outcome, useAjax);
}

function adjustContentHeight() {
    Apperyio.adjustContentHeightWithPadding();
}

function adjustContentHeightWithPadding(_page) {
    Apperyio.adjustContentHeightWithPadding(_page);
}

function setDetailContent(pageUrl) {
    Apperyio.setDetailContent(pageUrl);
}

Apperyio.AppPages = [{
    "name": "singIn",
    "location": "singIn.html"
}, {
    "name": "ContactsScreen",
    "location": "ContactsScreen.html"
}, {
    "name": "Twilio_Send",
    "location": "Twilio_Send.html"
}, {
    "name": "startPage",
    "location": "startPage.html"
}, {
    "name": "Twilio_Messages",
    "location": "Twilio_Messages.html"
}, {
    "name": "updateDB_page",
    "location": "updateDB_page.html"
}];

function updateDB_page_js() {

    /* Object & array with components "name-to-id" mapping */
    var n2id_buf = {
        'mobilebutton_12': 'updateDB_page_mobilebutton_12',
        'logout_button': 'updateDB_page_logout_button',
        'input_dogpark': 'updateDB_page_input_dogpark',
        'mobilebutton_4': 'updateDB_page_mobilebutton_4',
        'mobilelist_13': 'updateDB_page_mobilelist_13',
        'mobilelistitem_14': 'updateDB_page_mobilelistitem_14',
        'dogpark_name': 'updateDB_page_dogpark_name',
        'mobilelistitembutton_15': 'updateDB_page_mobilelistitembutton_15',
        'task_id': 'updateDB_page_task_id'
    };

    if ("n2id" in window && window.n2id !== undefined) {
        $.extend(n2id, n2id_buf);
    } else {
        window.n2id = n2id_buf;
    }

    /*
     * Nonvisual components
     */

    Apperyio.mappings = Apperyio.mappings || {};

    Apperyio.mappings["updateDB_page_item_add1_onsuccess_mapping_0"] = {
        "homeScreen": "updateDB_page",
        "directions": []
    };

    Apperyio.mappings["updateDB_page_item_add1_onbeforesend_mapping_0"] = {
        "homeScreen": "updateDB_page",
        "directions": [

        {
            "from_name": "userSessionToken",
            "from_type": "LOCAL_STORAGE",

            "to_name": "item_add1",
            "to_type": "SERVICE_REQUEST",

            "to_default": {
                "headers": {
                    "X-Appery-Database-Id": "{database_id}",
                    "Content-Type": "application/json"
                },
                "parameters": {},
                "body": null
            },

            "mappings": [

            {

                "source": "$",
                "target": "$['headers']['X-Appery-Session-Token']"

            }

            ]
        },

        {
            "from_name": "updateDB_page",
            "from_type": "UI",

            "to_name": "item_add1",
            "to_type": "SERVICE_REQUEST",

            "to_default": {
                "headers": {
                    "X-Appery-Database-Id": "{database_id}",
                    "Content-Type": "application/json"
                },
                "parameters": {},
                "body": null
            },

            "mappings": [

            {

                "source": "$['input_dogpark:text']",
                "target": "$['body']['location']"

            }

            ]
        }

        ]
    };

    Apperyio.mappings["updateDB_page_user_logout_onbeforesend_mapping_0"] = {
        "homeScreen": "updateDB_page",
        "directions": [

        {
            "from_name": "userSessionToken",
            "from_type": "LOCAL_STORAGE",

            "to_name": "user_logout",
            "to_type": "SERVICE_REQUEST",

            "to_default": {
                "headers": {
                    "X-Appery-Database-Id": "{database_id}"
                },
                "parameters": {},
                "body": null
            },

            "mappings": [

            {

                "source": "$",
                "target": "$['headers']['X-Appery-Session-Token']"

            }

            ]
        }

        ]
    };

    Apperyio.mappings["updateDB_page_user_logout_onsuccess_mapping_0"] = {
        "homeScreen": "updateDB_page",
        "directions": []
    };

    Apperyio.mappings["updateDB_page_item_delete_onsuccess_mapping_0"] = {
        "homeScreen": "updateDB_page",
        "directions": []
    };

    Apperyio.mappings["updateDB_page_item_delete_onbeforesend_mapping_0"] = {
        "homeScreen": "updateDB_page",
        "directions": [

        {
            "from_name": "taskId",
            "from_type": "LOCAL_STORAGE",

            "to_name": "item_delete",
            "to_type": "SERVICE_REQUEST",

            "to_default": {
                "headers": {
                    "X-Appery-Database-Id": "{database_id}"
                },
                "parameters": {},
                "body": null
            },

            "mappings": [

            {

                "source": "$",
                "target": "$['parameters']['_id']"

            }

            ]
        }

        ]
    };

    Apperyio.mappings["updateDB_page_item_list_onbeforesend_mapping_0"] = {
        "homeScreen": "updateDB_page",
        "directions": [

        {

            "to_name": "item_list",
            "to_type": "SERVICE_REQUEST",

            "to_default": {
                "headers": {
                    "X-Appery-Database-Id": "{database_id}"
                },
                "parameters": {},
                "body": null
            },

            "mappings": []
        }

        ]
    };

    Apperyio.mappings["updateDB_page_item_list_onsuccess_mapping_0"] = {
        "homeScreen": "updateDB_page",
        "directions": [

        {
            "from_name": "item_list",
            "from_type": "SERVICE_RESPONSE",

            "to_name": "updateDB_page",
            "to_type": "UI",

            "mappings": [

            {

                "source": "$['body'][i]",
                "target": "$['mobilelistitem_14']"

            },

            {

                "source": "$['body'][i]['location']",
                "target": "$['mobilelistitem_14']['dogpark_name:text']"

            },

            {

                "source": "$['body'][i]['_id']",
                "target": "$['mobilelistitem_14']['task_id:text']"

            }

            ]
        }

        ]
    };

    Apperyio.mappings["updateDB_page_item_add_onsuccess_mapping_0"] = {
        "homeScreen": "updateDB_page",
        "directions": []
    };

    Apperyio.mappings["updateDB_page_item_add_onbeforesend_mapping_0"] = {
        "homeScreen": "updateDB_page",
        "directions": [

        {
            "from_name": "updateDB_page",
            "from_type": "UI",

            "to_name": "item_add",
            "to_type": "SERVICE_REQUEST",

            "to_default": {
                "headers": {
                    "X-Appery-Database-Id": "{database_id}",
                    "Content-Type": "application/json"
                },
                "parameters": {},
                "body": null
            },

            "mappings": [

            {

                "source": "$['input_dogpark:text']",
                "target": "$['body']['location']"

            }

            ]
        }

        ]
    };

    Apperyio.datasources = Apperyio.datasources || {};

    window.item_add1 = Apperyio.datasources.item_add1 = new Apperyio.DataSource(locations_ParkFinder_create_service, {
        "onBeforeSend": function(jqXHR) {
            Apperyio.processMappingAction(Apperyio.mappings["updateDB_page_item_add1_onbeforesend_mapping_0"]);
        },
        "onComplete": function(jqXHR, textStatus) {

        },
        "onSuccess": function(data) {
            Apperyio.processMappingAction(Apperyio.mappings["updateDB_page_item_add1_onsuccess_mapping_0"]);
            try {
                item_list2.execute({});
            } catch (e) {
                console.error(e);
                hideSpinner();
            };
        },
        "onError": function(jqXHR, textStatus, errorThrown) {}
    });

    window.user_logout = Apperyio.datasources.user_logout = new Apperyio.DataSource(locations_logout_service, {
        "onBeforeSend": function(jqXHR) {
            Apperyio.processMappingAction(Apperyio.mappings["updateDB_page_user_logout_onbeforesend_mapping_0"]);
        },
        "onComplete": function(jqXHR, textStatus) {

        },
        "onSuccess": function(data) {
            Apperyio.processMappingAction(Apperyio.mappings["updateDB_page_user_logout_onsuccess_mapping_0"]);
        },
        "onError": function(jqXHR, textStatus, errorThrown) {}
    });

    window.item_delete = Apperyio.datasources.item_delete = new Apperyio.DataSource(locations_ParkFinder_delete_service, {
        "onBeforeSend": function(jqXHR) {
            Apperyio.processMappingAction(Apperyio.mappings["updateDB_page_item_delete_onbeforesend_mapping_0"]);
        },
        "onComplete": function(jqXHR, textStatus) {

        },
        "onSuccess": function(data) {
            Apperyio.processMappingAction(Apperyio.mappings["updateDB_page_item_delete_onsuccess_mapping_0"]);
            try {
                item_list.execute({});
            } catch (e) {
                console.error(e);
                hideSpinner();
            };
        },
        "onError": function(jqXHR, textStatus, errorThrown) {}
    });

    window.item_list2 = Apperyio.datasources.item_list2 = new Apperyio.DataSource(locations_ParkFinder_list_service, {
        "onBeforeSend": function(jqXHR) {},
        "onComplete": function(jqXHR, textStatus) {

        },
        "onSuccess": function(data) {},
        "onError": function(jqXHR, textStatus, errorThrown) {}
    });

    window.item_list = Apperyio.datasources.item_list = new Apperyio.DataSource(locations_ParkFinder_list_service, {
        "onBeforeSend": function(jqXHR) {
            Apperyio.processMappingAction(Apperyio.mappings["updateDB_page_item_list_onbeforesend_mapping_0"]);
        },
        "onComplete": function(jqXHR, textStatus) {

        },
        "onSuccess": function(data) {
            Apperyio.processMappingAction(Apperyio.mappings["updateDB_page_item_list_onsuccess_mapping_0"]);
        },
        "onError": function(jqXHR, textStatus, errorThrown) {}
    });

    window.item_add = Apperyio.datasources.item_add = new Apperyio.DataSource(locations_ParkFinder_create_service, {
        "onBeforeSend": function(jqXHR) {
            Apperyio.processMappingAction(Apperyio.mappings["updateDB_page_item_add_onbeforesend_mapping_0"]);
        },
        "onComplete": function(jqXHR, textStatus) {

        },
        "onSuccess": function(data) {
            Apperyio.processMappingAction(Apperyio.mappings["updateDB_page_item_add_onsuccess_mapping_0"]);
            try {
                item_list.execute({});
            } catch (e) {
                console.error(e);
                hideSpinner();
            };
        },
        "onError": function(jqXHR, textStatus, errorThrown) {}
    });

    Apperyio.CurrentScreen = 'updateDB_page';
    _.chain(Apperyio.mappings).filter(function(m) {
        return m.homeScreen === Apperyio.CurrentScreen;
    }).each(Apperyio.UIHandler.hideTemplateComponents);

    /*
     * Events and handlers
     */

    // On Load
    var updateDB_page_onLoad = function() {
            updateDB_page_elementsExtraJS();

            try {
                item_list.execute({});
            } catch (e) {
                console.error(e);
                hideSpinner();
            };

            updateDB_page_deviceEvents();
            updateDB_page_windowEvents();
            updateDB_page_elementsEvents();
        };

    // screen window events


    function updateDB_page_windowEvents() {

        $('#updateDB_page').bind('pageshow orientationchange', function() {
            var _page = this;
            adjustContentHeightWithPadding(_page);
        });
        $('#updateDB_page').on({
            pageshow: function(event) {
                try {
                    item_list2.execute({});
                } catch (e) {
                    console.error(e);
                    hideSpinner();
                };
            },
        });

    };

    // device events


    function updateDB_page_deviceEvents() {
        document.addEventListener("deviceready", function() {

        });
    };

    // screen elements extra js


    function updateDB_page_elementsExtraJS() {
        // screen (updateDB_page) extra code

        /* mobilelist_13 */

        listView = $("#updateDB_page_mobilelist_13");
        theme = listView.attr("data-theme");
        if (typeof theme !== 'undefined') {
            var themeClass = "ui-btn-up-" + theme;
            listItem = $("#updateDB_page_mobilelist_13 .ui-li-static");
            $.each(listItem, function(index, value) {
                $(this).addClass(themeClass);
            });
        }

        /* mobilelistitem_14 */

    };

    // screen elements handler


    function updateDB_page_elementsEvents() {
        $(document).on("click", "a :input,a a,a fieldset label", function(event) {
            event.stopPropagation();
        });

        $(document).off("click", '#updateDB_page_update_page [name="mobilebutton_12"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('startPage', {
                        reverse: false
                    });

                }
            },
        }, '#updateDB_page_update_page [name="mobilebutton_12"]');
        $(document).off("click", '#updateDB_page_update_page [name="logout_button"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('singIn', {
                        reverse: false
                    });

                }
            },
        }, '#updateDB_page_update_page [name="logout_button"]');

        $(document).off("click", '#updateDB_page_mobilecontainer [name="mobilebutton_4"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    try {
                        item_add.execute({});
                    } catch (e) {
                        console.error(e);
                        hideSpinner();
                    };

                }
            },
        }, '#updateDB_page_mobilecontainer [name="mobilebutton_4"]');

        $(document).off("click", '#updateDB_page_mobilecontainer [name="mobilelistitem_14"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    try {
                        $a.storage["taskId"].update("$", $a.c15r($a.UIHandler.resolveGeneratedComponent('task_id', this), 'get', 'text'))
                    } catch (e) {
                        console.error(e)
                    };
                    try {
                        item_delete.execute({});
                    } catch (e) {
                        console.error(e);
                        hideSpinner();
                    };

                }
            },
        }, '#updateDB_page_mobilecontainer [name="mobilelistitem_14"]');

    };

    $(document).off("pagebeforeshow", "#updateDB_page").on("pagebeforeshow", "#updateDB_page", function(event, ui) {
        Apperyio.CurrentScreen = "updateDB_page";
        _.chain(Apperyio.mappings).filter(function(m) {
            return m.homeScreen === Apperyio.CurrentScreen;
        }).each(Apperyio.UIHandler.hideTemplateComponents);
    });

    updateDB_page_onLoad();
};

$(document).off("pagecreate", "#updateDB_page").on("pagecreate", "#updateDB_page", function(event, ui) {
    Apperyio.processSelectMenu($(this));
    updateDB_page_js();
});